version: '3'
services:
  web:
    image: klakegg/hugo:ext-alpine
    command: server --verbose --watch --buildFuture --buildDrafts --disableFastRender -D --bind 0.0.0.0
    ports:
      - "1313:1313"
    volumes:
      - ".:/src"