version: '3'
services:
  web:
    build: .
    ports:
      - "1313:1313"
    volumes:
      - .:/web
    command: hugo server --verbose --watch --buildFuture --buildDrafts --disableFastRender -D --bind 0.0.0.0