services:
  web:
    image: klakegg/hugo:ext-alpine
    command: server --gc --verbose --watch --buildFuture --buildDrafts --disableFastRender -D
    ports:
      - "1313:1313"
    volumes:
      - ".:/src"
